<?php

/**
 * @file
 * Module file for Hyperaudio for Developers
 *
 * This file serves as a stub file for the many Examples modules in the
 * @link http://github.com/hyperaudio/drupal Examples for Developers Project @endlink
 * which you can download and experiment with.
 *
 * One might say that examples.module is an example of documentation. However,
 * note that the example submodules define many doxygen groups, which may or
 * may not be a good strategy for other modules.
 */

use Drupal\Core\Url;

/**
 * @defgroup Hyperaudio
 * @{
 * Hyperaudio Modules
 */

/**
 * Implements hook_toolbar().
 */
function examples_toolbar() {

  $examples = array(
    'hyperaudio_player' => 'hyperaudio_player.description',
  );

  // Build a list of links for the menu.
  $links = array();
  foreach ($examples as $module => $route) {
    // Get the module info (title, description) from Drupal.
    $info = system_get_info('module', $module);

    // If there's no info, the example isn't enabled, so don't display it.
    if (!empty($info)) {
      $links[$module] = array(
        'title' => t($info['name']),
        'url' => Url::fromRoute($route),
        'attributes' => array(
          'title' => t($info['description']),
        ),
      );
    }
  }

  // Add a link to enable all examples.
  $links['enable_examples'] = array(
    'title' => t('Enable Hyperaudio'),
    'url' => Url::fromRoute('system.modules_list'),
    'options' => array(
      'title' => t('Enable Hyperaudio on the Extend page.'),
    ),
    'fragment' => 'edit-modules-example-modules',
  );

  // Create the examples toolbar render array.
  $items['examples'] = array(
    '#type' => 'toolbar_item',
    'tab' => array(
      '#type' => 'link',
      '#title' => t('Hyperaudio'),
      // @todo: Once it is created, use the example index page.
      '#url' => Url::fromRoute('<front>'),
      '#attributes' => array(
        'title' => t('Hyperaudio Developer Examples'),
        'class' => array('toolbar-icon', 'toolbar-icon-examples'),
      ),
    ),
    'tray' => array(
      '#heading' => t('Hyperaudio Developer Examples'),
      'shortcuts' => array(
        '#theme' => 'links__toolbar_example',
        '#links' => $links,
        '#attributes' => array(
          'class' => array('toolbar-menu'),
        ),
      ),
    ),
    '#weight' => 99,
    '#attached' => array(
      'library' => array(
        'hyperaudio/hyperaudio.icons',
      ),
    ),
  );

  return $items;
}

/**
 * @} End of 'defgroup examples'.
 */
