<?php

/**
 * @file
 * Hyperaudio Player module.
 *
 */

/**
 * Implements hook_theme().
 */
function hyperaudio_player_theme() {
  return [
    'hyperaudio_player_output' => [
      'variables' => [
        'mode' => NULL,
        'metadata' => NULL,
        'selection' => NULL,
        'player_class' => NULL,
        'player_style' => NULL,
        'player_selector' => NULL,
        'media' => NULL,
        'poster' => NULL,
        'transcript' => NULL,
        'transcript_class' => NULL,
        'transcript_style' => NULL,
        'transcript_selector' => NULL,
        'fb_app_id' => NULL,
        'fb_admins' => NULL,
        'tw_site' => NULL,
        'site_name' => NULL,
      ],
      'template' => 'hyperaudio-player-output',
    ],
  ];
}

function metaTag(array &$page, $name, $value) {
  if (!isset($value) && $value != '') return;

  $page['#attached']['html_head'][] = [
    array(
      '#tag' => 'meta',
      '#attributes' => array(
        'property' => $name,
        'content' => $value,
      )
    ),
    'og' . ucfirst($name)
  ];
}

function hyperaudio_player_page_attachments(array &$page) {
  if (!isset($page)) return;
  $uri = \Drupal::request()->getUri();
  $hash = sha1($uri);

  $tempstore = \Drupal::service('user.private_tempstore')->get('hyperaudio_player~' . $hash);
  if (!isset($tempstore)) return;
  if (!$tempstore->get('metadata')) return; // should work for 0 too
  if ($tempstore->get('metadata') == 1 && null != \Drupal::request()->query->get('t')) return;

  $media = $tempstore->get('media');
  $media_width = $tempstore->get('media_width');
  $media_height = $tempstore->get('media_height');

  $poster = $tempstore->get('poster');
  $poster_width = $tempstore->get('poster_width');
  $poster_height = $tempstore->get('poster_height');

  $title = $tempstore->get('title');
  $desc = $tempstore->get('desc');
  $uri = $current_uri;

  $fb_app_id = $tempstore->get('fb_app_id');
  $fb_admins = $tempstore->get('fb_admins');
  $tw_site = $tempstore->get('tw_site');
  $site_name = $tempstore->get('site_name');

  metaTag($page, "og:locale", "en_US");
  metaTag($page, "og:title", $title);

  metaTag($page, "og:site_name", $site_name);
  metaTag($page, "og:type", "video.other"); // FIXME

  metaTag($page, "og:description", $desc);
  metaTag($page, "og:url", $uri);

  metaTag($page, "og:video:url", $media);
  metaTag($page, "og:video:secure_url", $media);
  metaTag($page, "og:video:width", $media_width);
  metaTag($page, "og:video:height", $media_height);
  metaTag($page, "og:video:type", "video/mp4"); // FIXME

  metaTag($page, "og:image", $poster);
  metaTag($page, "og:image:width", $poster_width);
  metaTag($page, "og:image:height", $poster_height);

  metaTag($page, "fb:app_id", $fb_app_id);
  metaTag($page, "fb:admins", $fb_admins);

  metaTag($page, "twitter:card", "summary");
  metaTag($page, "twitter:site", $tw_site);
  metaTag($page, "twitter:title", $title);
  metaTag($page, "twitter:description", $desc);
  metaTag($page, "twitter:image", $poster);
}
