<?php

/**
 * @file
 * Examples showing how to use some of the new JavaScript features in Drupal 8.
 */

/**
 * @defgroup js_example Example: JavaScript
 * @ingroup examples
 * @{
 * Examples using Drupal 8's built-in JavaScript.
 *
 * We have two examples here.
 *
 * One 'weights' content and then sorts it by weight. This demonstrates
 * attaching JavaScript through Drupal's render arrays.
 *
 * The other demonstrates adding an accordion effect to content, through
 * Drupal's theme layer.
 */

/**
 * Implements hook_theme().
 */
function ha_pad_theme() {
  return array(
    'ha_pad_pad' => array(
      'template' => 'pad',
      'variables' => array('transcript' => NULL, 'media' => null, 'title' => null, 'variant' => null,),
    ),
  );
}

//function ogProp(array &$page, $name, $value) {
//  $page['#attached']['html_head'][] = [array('#tag' => 'meta', '#attributes' => array(
//    'property' => 'og:' . $name,
//    'content' => $value,
//  )), 'og' . ucfirst($name)];
//}

//function ha_pad_page_attachments(array &$page) {
//  ogProp($page, "locale", "en_US");
//  ogProp($page, "title", "Studs Terkel talks with Jane Stedman (1965)");
//  ogProp($page, "site_name", "Studs Terkel Radio Archive");
//  ogProp($page, "type", "video.other");
//  ogProp($page, "description", "Make way for the prize-men, for the Wise Men they are prize-men - double first men of the university! This is the first big entrance in a Gilbert and Sullivan operetta that was never produced in England by D'Oyly Carte, rarely produce.");
//  ogProp($page, "url", "https://dev-stra.pantheonsite.io/hyperaudio/pad/rojWGnK_Q0-xd9WRuPP04A");
////  ogProp($page, "video", "https://s3.amazonaws.com/wfmt-studs-terkel/published/14103.mp4");
//  ogProp($page, "video:url", "https://s3.amazonaws.com/wfmt-studs-terkel/published/14103.mp4");
//  ogProp($page, "video:secure_url", "https://s3.amazonaws.com/wfmt-studs-terkel/published/14103.mp4");
//  ogProp($page, "video:width", "1280");
//  ogProp($page, "video:height", "720");
//  ogProp($page, "video:type", "video/mp4");
//
//  ogProp($page, "image", "https://via.placeholder.com/1280x720");
//  ogProp($page, "image:width", "1280");
//  ogProp($page, "image:height", "720");
//
//  $page['#attached']['html_head'][] = [array('#tag' => 'meta', '#attributes' => array(
//    'property' => 'fb:app_id',
//    'content' => "177867219463585",
//  )), 'fbApp_id'];
//  $page['#attached']['html_head'][] = [array('#tag' => 'meta', '#attributes' => array(
//    'property' => 'fb:admins',
//    'content' => "754413412",
//  )), 'fbAdmins'];
//
//}

/**
 * @} End of "defgroup js_example".
 */
