<?php

/**
 * @file
 * Examples showing how to use some of the new JavaScript features in Drupal 8.
 */

/**
 * @defgroup js_example Example: JavaScript
 * @ingroup examples
 * @{
 * Examples using Drupal 8's built-in JavaScript.
 *
 * We have two examples here.
 *
 * One 'weights' content and then sorts it by weight. This demonstrates
 * attaching JavaScript through Drupal's render arrays.
 *
 * The other demonstrates adding an accordion effect to content, through
 * Drupal's theme layer.
 */

/**
 * Implements hook_theme().
 */
function ha_player_theme() {
  return array(
    'ha_player_player' => array(
      'template' => 'player',
      'variables' => array('transcript' => NULL, 'media' => null, 'title' => null, 'variant' => null,),
    ),
  );
}

function metaTag(array &$page, $name, $value) {
  $page['#attached']['html_head'][] = [array('#tag' => 'meta', '#attributes' => array(
    'property' => $name,
    'content' => $value,
  )), 'og' . ucfirst($name)];
}

function ha_player_page_attachments(array &$page) {

  $tempstore = \Drupal::service('user.private_tempstore')->get('ha_player');
  $media = $tempstore->get('media');
  $title = $tempstore->get('title');
  $desc = $tempstore->get('desc');
  $uri = $tempstore->get('uri');

  metaTag($page, "og:locale", "en_US");
  metaTag($page, "og:title", $title);
  metaTag($page, "og:site_name", "Studs Terkel Radio Archive");
  metaTag($page, "og:type", "video.other");
  metaTag($page, "og:description", $desc);
  metaTag($page, "og:url", $uri);
  metaTag($page, "og:video:url", $media);
  metaTag($page, "og:video:secure_url", $media);
  metaTag($page, "og:video:width", "1280");
  metaTag($page, "og:video:height", "720");
  metaTag($page, "og:video:type", "video/mp4");

  metaTag($page, "og:image", "https://lab.hyperaud.io/temp/studsposter.png");
  metaTag($page, "og:image:width", "640");
  metaTag($page, "og:image:height", "361");

  metaTag($page, "fb:app_id", "177867219463585");
  metaTag($page, "fb:admins", "754413412");

//  $page['#attached']['html_head'][] = [array('#tag' => 'meta', '#attributes' => array(
//    'property' => 'fb:app_id',
//    'content' => "177867219463585",
//  )), 'fbApp_id'];
//  $page['#attached']['html_head'][] = [array('#tag' => 'meta', '#attributes' => array(
//    'property' => 'fb:admins',
//    'content' => "754413412",
//  )), 'fbAdmins'];

  metaTag($page, "twitter:card", "summary");
  metaTag($page, "twitter:site", "@studsarchive");
  metaTag($page, "twitter:title", $title);
  metaTag($page, "twitter:description", $desc);
  metaTag($page, "twitter:image", "https://lab.hyperaud.io/temp/studsposter.png");

}

/**
 * @} End of "defgroup js_example".
 */
